### PR TITLE
CI/CD: Benchmarking test - using latest version

### LINKED ISSUE #2: Add CI/CD tests
Hi @batiati,

Do you want to add tests to the GH actions?

I don't know if they've fixed the problem with `run_with_tb`. However, I'm already working on an alternative solution to make the tests better available on the CI/CD.
- https://github.com/tigerbeetle/tigerbeetle/issues/794

And also present a "jabá" (propaganda) about cmake in C and/or C++ tb_projects.
**[WIP]:** https://github.com/batiati/tigerbeetle-clients-benchmarks/compare/master...kassane:tigerbeetle-clients-benchmarks:upstream

### PR DESCRIPTION
**Pull request by kassane**
closes: #2

**Note:** According to this example, the C client that uses CMake eventually gets the latest version of TB downloaded and compiled, independently of the previously built source for the other clients.

preview: https://github.com/kassane/tigerbeetle-clients-benchmarks/actions

### CODE REVIEW

**Comment by kassane** [comment]
Need refactoring some clients: Go, Java and .Net
Refactored: Zig and C

**Comment by kassane** [comment]
@batiati ,

Whenever possible, I'll need your help to refactor the other clients.
Although not very experienced in these languages, I have also not followed the changes in these apis.

**Note:** This PR, has marked "Allow edits and access to secrets by maintainers."

**Comment by kassane** [comment]
### Fixed

- Go client,
- Zig client
- C client

### New

- D client (BetterC [nogc]) posix style (thx @jacob-carlborg **dstep** bindgen)

---

https://github.com/kassane/tigerbeetle-clients-benchmarks/actions/runs/7078576026/job/19264212020

<details>
<summary>C result</summary>

```bash
$> [100%] Linking C executable bench
[100%] Built target bench
info(message_bus): connected to replica 0
Total time: 3113 ms
Max time per batch: 103 ms
Transfers per second: 321233

Total time: 3010 ms
Max time per batch: 26 ms
Transfers per second: 332225

Total time: 3086 ms
Max time per batch: 46 ms
Transfers per second: 324044

Total time: 3055 ms
Max time per batch: 33 ms
Transfers per second: 327332

Total time: 3027 ms
Max time per batch: 27 ms
Transfers per second: 330360

Total time: 3036 ms
Max time per batch: 35 ms
Transfers per second: 329380

Total time: 3039 ms
Max time per batch: 28 ms
Transfers per second: 329055

Total time: 3033 ms
Max time per batch: 30 ms
Transfers per second: 329706

Total time: 3028 ms
Max time per batch: 26 ms
Transfers per second: 330250

Total time: 3028 ms
Max time per batch: 27 ms
Transfers per second: 330250

[100%] Built target run
```
</details>

<details>
<summary>Go result</summary>

```bash
$> Run cd go
go: downloading github.com/tigerbeetle/tigerbeetle-go v0.14.167
info(message_bus): connected to replica 0
Total time: 2981 ms
Max time per batch: 98 ms
Transfers per second: 335457

Total time: 2890 ms
Max time per batch: 29 ms
Transfers per second: 346020

Total time: 2900 ms
Max time per batch: 26 ms
Transfers per second: 344827

Total time: 2898 ms
Max time per batch: 32 ms
Transfers per second: 345065

Total time: 2902 ms
Max time per batch: 26 ms
Transfers per second: 344589

Total time: 2930 ms
Max time per batch: 29 ms
Transfers per second: 341296

Total time: 2908 ms
Max time per batch: 26 ms
Transfers per second: 343878

Total time: 2891 ms
Max time per batch: 25 ms
Transfers per second: 345901

Total time: 2911 ms
Max time per batch: 33 ms
Transfers per second: 343524

Total time: 2938 ms
Max time per batch: 64 ms
Transfers per second: 340367
```
</details>

<details>
<summary>D result</summary>

```bash
$> Run cd d
    Starting Performing "release" build using /opt/hostedtoolcache/dc/ldc2-1.35.0/x64/ldc2-1.35.0-linux-x86_64/bin/ldc2 for x86_64.
    Building tb_client_bench ~master: building configuration [application]
     Linking tb_client_bench
     Running bin/tb_client_bench 
info(message_bus): connected to replica 0
Total time: 3110 ms
Max time per batch: 107 ms
Transfers per second: 321543

Total time: 3037 ms
Max time per batch: 32 ms
Transfers per second: 329272

Total time: 3028 ms
Max time per batch: 28 ms
Transfers per second: 330250

Total time: 3017 ms
Max time per batch: 27 ms
Transfers per second: 331455

Total time: 3019 ms
Max time per batch: 26 ms
Transfers per second: 331235

Total time: 3033 ms
Max time per batch: 30 ms
Transfers per second: 329706

Total time: 3027 ms
Max time per batch: 29 ms
Transfers per second: 330360

Total time: 3020 ms
Max time per batch: 26 ms
Transfers per second: 331125

Total time: 3025 ms
Max time per batch: 28 ms
Transfers per second: 330578

Total time: 3025 ms
Max time per batch: 27 ms
Transfers per second: 330578
```
</details>

<details>
<summary>Zig result</summary>

```bash
$> Run cd zig
info(message_bus): connected to replica 0
Total time: 922 ms
Max time per batch: 595 ms
Transfers per second: 1084598

Total time: 313 ms
Max time per batch: 4 ms
Transfers per second: 3194888

Total time: 326 ms
Max time per batch: 13 ms
Transfers per second: 3067484

Total time: 326 ms
Max time per batch: 11 ms
Transfers per second: 3067484

Total time: 322 ms
Max time per batch: 5 ms
Transfers per second: 3105590

Total time: 327 ms
Max time per batch: 4 ms
Transfers per second: 3058103

Total time: 317 ms
Max time per batch: 4 ms
Transfers per second: 3154574

Total time: 319 ms
Max time per batch: 4 ms
Transfers per second: 3134796

Total time: 315 ms
Max time per batch: 11 ms
Transfers per second: 3174603

Total time: 319 ms
Max time per batch: 7 ms
Transfers per second: 3134796
```
</details>

**Comment by kassane** [comment]
Finally, done all samples!! 🥳😅

**Comment by batiati** [comment]
Wow!!! Impressive work, thanks so much for keeping this project updated!

**Pull request merged**
